batch_size: 5
num_samples: 15
num_epochs: 3000


optim:
  optimizer: adam
  weight_decay: 0.0
  momentum: 0.9

  lr:
    scheduler: cos
    anneal_step: 100
    anneal_factor: 0.9
    warmup_steps: 50
    cos_T: 200
    cos_min: 1e-8

  lr_l: 0.0
  lr_i: 0.0001
  lr_o: 0.0001
    

mu:
  init: 150.0
  step: 1
  step_size: 0.1
  max: 150.0
  min: 0.0
  value: 1.0
  warmup: 100

entr_coef: 10.0
loss_config: "normalize"